// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    return $("#send").click(function() {
      return $.post("/system/createIssue", $("#form_issue").serializeObject(), function(t) {
        if (t === '1') {
          return alert("Enviado com sucesso!");
        } else {
          return alert("Erro ao enviar, tente novamente!");
        }
      }, "text");
    });
  });

}).call(this);
