// Generated by CoffeeScript 1.6.3
(function() {
  var Manager;

  Manager = (function() {
    function Manager() {}

    Manager.remove = function(id) {
      var url;
      if(confirm('Tem certeza que deseja excluir o bloqueio?')){
        url = "/calendar/remove_freebusy/" + id;
        return $.get(url, function() {
          alert("Excluído com sucesso!");
          return Manager.getListFromServer();
        });
      }
    };

    Manager.getUsers = function() {
      var url;
      url = "/cash/getUsers";
      return $.get(url, function(t) {
        var obj, _i, _len, _results;
        eval("userObj = " + t);
        $('#user, #user_filter').append("<option value='SELECT_ALL'>Todos</option>");
        _results = [];
        for (_i = 0, _len = userObj.length; _i < _len; _i++) {
          obj = userObj[_i];
          _results.push($('#user, #user_filter').append("<option value='" + obj.id + "'>" + obj.name + "</option>"));
        }
        return _results;
      });
    };

    Manager.startDate = function() {
      return encodeURIComponent($("#start_date").val());
    };

    Manager.endDate = function() {
      return encodeURIComponent($("#end_date").val());
    };

    Manager.users = function() {
      var users;
      users = $("#user_filter").val();
      if (users) {
        return encodeURIComponent(users.join(','));
      } else {
        "0";
        return "0";
      }
    };

    Manager.getListFromServer = function() {
      var show_work_hours;
      show_work_hours = $('#show_work_hours').is(':checked');
      return $.get("/calendar/allfreebusy/" + (Manager.startDate()) + "/" + (Manager.endDate()) + "?users=" + (Manager.users()) + "&showWorkHours=" + show_work_hours, function(results) {
        var obj, total, _i, _len;
        eval("results = " + results);
        Manager.list = results;
        $("#grid tbody").html("");
        total = 0;
        for (_i = 0, _len = results.length; _i < _len; _i++) {
          obj = results[_i];
          $("#grid tbody").append("<tr><td>" + obj.user + "</td><td>" + (getDateBr(new Date(obj.start))) + " " + (getHourBr(new Date(obj.start))) + "</td><td>" + (getDateBr(new Date(obj.end))) + " " + (getHourBr(new Date(obj.end))) + "</td><td>" + obj.obs + "</td></td><td><a href='#' data-id='" + obj.id + "' class='action_delete'><img src='/images/delete.png'/></a></td></tr>");
        }
        return $(".action_delete").click(function() {
          return Manager.remove($(this).attr("data-id"));
        });
      });
    };

    Manager.save = function() {
      var end, obs, start, user;
      start = $("#start").val() + " " + $("#hour_start").val();
      end = $("#end").val() + " " + $("#hour_end").val();
      user = $("#user").val();
      obs = $("#obs").val();
      if (!$("#start").val() || !$("#hour_start").val() || !$("#end").val() || !$("#hour_end").val() || !user) {
        return alert('Verifique os dados obrigatórios!');
      } else {
        return $.post("/calendar/freebusy", {
          "start": start,
          "end": end,
          "user": user,
          "obs": obs
        }, function(t) {
          alert("Cadastrado com sucesso");
          $("#account_modal").modal({
            "hide": true
          });
          return Manager.getListFromServer();
        });
      }
    };

    return Manager;

  })();

  $(function() {
    $("#new").click(function() {
      return $("#account_modal").modal({
        "show": true,
        "keyboard": true,
        "backdrop": true
      });
    });
    $(".b_add_account").click(function() {
      return Manager.save();
    });
    $("#start_date").val(new Date().getDateBr());
    $("#end_date").val(new Date().getDateBr());
    Manager.getUsers();
    Manager.getListFromServer();
    $("#send").click(function() {
      return Manager.getListFromServer();
    });
    return $("#start_date,#end_date").change(function() {
      //return Manager.getListFromServer();
    });
  });

}).call(this);
