// Generated by CoffeeScript 1.6.3
(function () {
  var IcdSearch, icon_tag, page_html;
  var parent_icd_search = null;

  icon_tag = '<a href="#"><img src="/images/search.png" width="16" class="icd_search"></a>';

  page_html =
    "<div class=\"modal hide fade icd_search_popup\" id=\"icd_search_popup\">\n    <div class=\"modal-header\">\n            <a class=\"close\" href=\"#\">×</a>\n          <h3>Buscar de Produtos</h3>\n    </div>\n    <div class=\"modal-body \">\n    <form>\n          <div class=\"well\">\n            <input value=\"Buscar\" type=\"button\" class=\"btn success icd_search_send\">\n          </div>    \n            <span>\n              <div class=\"clearfix\">\n                <label for=\"name\">Codigo</label>\n                 <div class=\"input\">\n                    <input class=\"medium icd_search_id\" size=\"30\" type=\"text\" value=\"\">\n                    <span class=\"help-block\">Codigo do Produto</span>\n                 </div>\n              </div>            \n              <div class=\"clearfix\">\n                <label for=\"name\">Nome</label>\n                 <div class=\"input\">\n                    <input class=\"medium icd_search_name\" size=\"30\" type=\"text\" value=\"\">\n                    <span class=\"help-block\">Nome completo</span>\n                 </div>\n              </div>\n              <div class=\"clearfix\">\n                <label for=\"name\">Codigo Externo</label>\n                 <div class=\"input\">\n                    <input class=\"medium external_id\" size=\"30\" type=\"text\"/>\n                    <span class=\"help-block\">Codigo para busca simplificada</span>\n                 </div>\n              </div>               \n            </span>\n        </form> \n        <table class=\"zebra-striped\" id=\"table_icd_search\">\n        </table>    \n   </div>\n   <div class=\"modal-footer\">\n   </div>\n</div>";

  IcdSearch = (function () {
    function IcdSearch() {}

    return IcdSearch;

  })();

  IcdSearch.selectIcdListeners = [];

  window.IcdSearch = IcdSearch;

  IcdSearch.selectAutoCompleteName = function (icd, defOption) {
    IcdSearch.selectSearchIcd(icd, icd.name, true, defOption);
    return icd.name;
  };

  IcdSearch.updatePrice = function () {
    if (IcdSearch.selectedIcd) {
      return IcdSearch.selectSearchIcd(IcdSearch.selectedIcd, true, {});
    }
  };

  IcdSearch.selectSearchIcd = function (icd, call_change, defOption) {
    IcdSearch.selectedIcd = icd;
    $("#icd_search_popup").modal("hide");
    $(window.current_icd_search_input).val(icd.id);
    if (defOption.userThuch) {
      $(".select2-container span", window.current_icd_search).html(icd.name);
    }
    $(".name_icd_search", window.current_icd_search).val(icd.name);
    //updateInventory(defOption, icd.id, call_change);
    if (call_change) {
      $(window.current_icd_search_input).change();
    }
    return IcdSearch.selectIcdListeners.map(function (listener) {
      return listener(icd);
    });
  };

  /*
  updateInventory = function (defOption, id) {
    var unit;
    if (defOption.updateInventory) {
      if (!defOption.allUnits) {
        if (defOption.unitField) {
          unit = $(defOption.unitField).val();
        } else {
          unit = 0;
        }
        return $.get("/inventory/currentstock/" + id + "/" + unit, function (ret) {
          return $(".inventory_icd_search").val(ret);
        });
      } else {
        return $.get("/inventory/currentstock/" + id, function (ret) {
          var content;
          eval("var data = " + ret);
          content = data.filter(function (item) {
            return item.amount > 0;
          }).map(function (item) {
            return "<tr><td>" + item.name + "</td><td>" + item.amount + "</td></tr>";
          });
          return $(".inventory_icd_search").html("<table class='bordered-table zebra-striped'>" + content.join('') + "</table>");
        });
      }
    }
  };
  */

  jQuery.fn.icdSearch = function (option) {
    var $field, bindPopup, defOption, searchInServer;
    $field = this;
    defOption = {
      createName: true,
      iconElement: false,
      //updateInventory: true,
      unitField: false,
      allUnits: false,
      userThuch: false,
      userFieldSelector: true
    };
    if (!option) {
      option = {};
    }
    $.extend(defOption, option);
    searchInServer = function (id, name, external_id, barcode, call_change) {
      var user;
      user = option.userFieldSelector ? $(option.userFieldSelector).val() : 0;
      return $.post("/icd/icd_search", {
        id: id,
        name: name,
        external_id: external_id,
        user: user,
        barcode: barcode
      }, function (r) {
        var obj, table, _i, _len;
        eval("var ret=" + r);
        table = "";
        if (ret.length > 0 && id !== "") {
          obj = ret[0];
          return IcdSearch.selectSearchIcd(obj, call_change, defOption);
        } else {
          for (_i = 0, _len = ret.length; _i < _len; _i++) {
            obj = ret[_i];
            table += "<tr><td>" + obj.id + "</td><td>" + obj.name + "</td><td><a class='icd_search_selector' data-id='" + obj.id + "' data-obj='" +
              (JSON.stringify(obj)) + "' data-name='" + obj.name + "' ><img src='/images/select.png' width='20'/></a></td></tr>";
          }
          $("#table_icd_search").html(table);
          return $('.icd_search_selector').click(function () {
            return IcdSearch.selectSearchIcd($(this).data("obj"), true, defOption);
          });
        }
      });
    };
    bindPopup = function () {
      if ($("#icd_search_popup").length <= 0) {
        $("body").append(page_html);
        $(".icd_search_send").click(function () {
          return searchInServer($(".icd_search_id").val(), $(".icd_search_name").val(), $('.external_id').val(), $('.barcode').val(), true);
        });
        return $("#icd_search_popup input").keydown(function (e) {
          if (e.keyCode === 13) {
            return searchInServer($(".icd_search_id").val(), $(".icd_search_name").val(), $('.external_id').val(), $('.barcode').val(), true);
          }
        });
      }
    };
    if (defOption.unitField) {
      $(defOption.unitField).change(function () {
        return updateInventory(defOption, $($field).val());
      });
    }
    this.change(function () {
      return searchInServer($(this).val(), "", "", false);
    });
    this.each(function () {
      var $parent, $icd_search;
      bindPopup();
      $parent = $(this).parent();
      window.current_icd_search = $parent;
      window.current_icd_search_input = this;
      if (!defOption.iconElement) {
        $parent.prepend(icon_tag);
      } else {
        $(defOption.iconElement, $parent).prepend(icon_tag);
      }
      if (defOption.createName) {
        $parent.append('<input class="span3 disabled name_icd_search" size="30" type="text" placeholder="Nome" disabled="">');
      }
      $icd_search = $(".icd_search", $parent);
      return $icd_search.click(function () {
        $("#icd_search_popup").modal({
          "backdrop": true,
          'keyboard': true,
          'show': true
        });
        return setTimeout(function () {
          return $(".icd_search_name").focus();
        }, 200);
      });
    });
    if (option.userThuch) {
      return this.each(function () {
        var field;
        $(this).data("prevalue", $(this).val());
        field = this;
        return $(this).select2({
          placeholder: "Digite o nome ou código do produto",
          minimumInputLength: 1,
          formatNoMatches: function (val) {
            return "Nenhum resultado";
          },
          id: function (a) {
            return a.name;
          },
          ajax: {
            url: "/icd/icd_search",
            dataType: 'text',
            quietMillis: 300,
            data: function (term, page) {
              var user;
              user = option.userFieldSelector ? $(option.userFieldSelector).val() : 0;
              return {
                name: term,
                page: page - 1,
                external_id: term,
                barcode: term,
                user: user
              };
            },
            results: function (data, page) {
              var parent_icd_search;
              eval('data=' + data);
              parent_icd_search = $(field).parent();
              return {
                results: data,
                more: data.length === 30
              };
            }
          },
          formatResult: function (icd) {
            return icd.name;
          },
          formatSelection: function (a) {
            $('.id_icd', parent_icd_search).val(a.id).change();
            return IcdSearch.selectAutoCompleteName(a, option);
          },
          dropdownCssClass: "bigdrop",
          escapeMarkup: function (m) {
            return m;
          }
        });
      });
    }
  };

}).call(this);
