// Generated by CoffeeScript 1.6.3

(function() {
  $(function() {
    return ProductLine.getListLineFromServer("#lines", function() {
      var str;
      str = $("#lines_id input").val();
      return $("#lines").val(str.split(",")).change();
    });
  });

}).call(this);
