// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    ProductLine.getListLineFromServer("#lines");
    ProductLine.getlistCategoryFromServer("#category_select");
    $(".product_select_thuch").productSearch({
      createName: false,
      iconElement: ".add-on",
      userThuch: true
    });
    $("#units").unitField(false, false);
    $("#brands").brandsField(true, false);
    return $("table").tablesorter();
  });

}).call(this);
