// Generated by CoffeeScript 1.3.1
(function() {
  var Product;

  Product = (function() {

    Product.name = 'Product';

    function Product() {}

    return Product;

  })();

  Product.getListLineFromServer = function(id, callback) {
    return $.get("/product/product_line", function(t) {
      var obj, ret, _i, _len;
      eval("var list = " + t);
      ret = "";
      for (_i = 0, _len = list.length; _i < _len; _i++) {
        obj = list[_i];
        ret += "<option value='" + obj.id + "'>" + obj.name + "</option>";
      }
      $(id).html(ret);
      if (callback) {
        return callback();
      }
    });
  };

  Product.getlistCategoryFromServer = function(id, callback) {
    return $.get("/product/product_category", function(t) {
      var obj, ret, _i, _len;
      eval("var list = " + t);
      ret = "";
      for (_i = 0, _len = list.length; _i < _len; _i++) {
        obj = list[_i];
        ret += "<option value='" + obj.id + "'>" + obj.name + "</option>";
      }
      $(id).html(ret);
      if (callback) {
        return callback();
      }
    });
  };

  window.ProductLine = Product;

}).call(this);
