// Generated by CoffeeScript 1.6.3
(function() {
  var ProductBOM;

  ProductBOM = (function() {
    function ProductBOM() {
      this.product = gup("id");
      this.product_bom = $("#product").val();
      this.obs = $("#obs_bom").val();
      this.qtd = $("#qtd").val();
      this.praceled = $("#praceled").is(':checked');
      this.price = $("#bom_salePrice").val();
      this.orderinreport = $("#orderinreport").val();
    }

    return ProductBOM;

  })();

  ProductBOM.list = [];

  ProductBOM.getListFromServer = function() {
    if (gup("id")) {
      return $.get("/product/" + (gup('id')) + "/product_bom/list", 
        function(results) {
        var obj, ret, _i, _len;
        var product_saleprice = 0.0;
        var item_price = 0.0;
        eval("results = " + results);
        ProductBOM.list = results;
        ret = "";
        for (_i = 0, _len = results.length; _i < _len; _i++) {
          obj = results[_i];
          ret += "<tr>\n  " + 
          "<td>" + obj.product_name + "</td>" +
          "<td>" + obj.qtd + "</td>" +
          "<td>" + obj.obs + "</td>" +
          "<td>" + (obj.price.formatMoney()) + "</td>" +
          "<td><img src=\"/images/" + (obj.parceled ? 'good' : 'bad') + ".png\"/></td>" +
          "<td>" + obj.orderinreport + "</td>" + 
          "<td><a data-id='" + obj.id + "' class='action_delete'><img src='/images/delete.png'/></a></td>" +
          "</tr>";
          item_price = (obj.price * obj.qtd)
          product_saleprice += item_price
        }

//        alert ($("#is_bomaux").val())
//        alert ($("#salePrice").val())
        var prprice = 0.0;
        prprice = $("#salePrice").val()
        if ($("#is_bomaux").val() == "true") {
          if (product_saleprice == 0.0) {
            alert ("O produto está marcado como pacote, mas não foi configurado com nenhum item\n\n" +
              "Insira os itens desejados na aba Configuração de Pacote")
          }
          if (prprice != product_saleprice && product_saleprice != 0.0) {
            if (confirm ("Preço de venda " + prprice + 
              "\nPreço config pacote " + product_saleprice + "\n\nAtualiza preço de venda?")) {         
              $("#salePrice").val(product_saleprice).change()
              $("#pr_salvar").click();
            }
          }
        } else {
          if (product_saleprice != 0.0) {
            alert ("O produto tem itens de configuração de pacote e não está marcado como tal\n\n" +
              "Marque o campo É um pacote? no produto, para que a configuralçao esteja completa")
            // podia fazer um confirm aqui e chmar uma api para setar o is_bom
            // true no product, não dá pra fazer como no salprice pq o snippet não
            // mante o name nem o id do checkbox 
          }
        }

        $("#grid tbody").html(ret);
        $("#product_salePrice").val((product_saleprice).formatMoney())
        return $(".action_delete").click(function() {
          return ProductBOM.remove($(this).data("id"));
        });
      });
    }
  };

  ProductBOM.getById = function(id) {
    var obj, _i, _len, _ref;
    _ref = ProductBOM.list;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      obj = _ref[_i];
      if (obj.id === parseInt(id)) {
        return obj;
      }
    }
  };

  ProductBOM.remove = function(id) {
    var error, success;
    success = function() {
      alert("Excluído com sucesso!");
      return ProductBOM.getListFromServer();
    };
    error = function() {
      return alert("Erro ao excluir serviço!");
    };
    return $.ajax("/product/product_bom/" + id, {
      "type": "DELETE",
      "success": success,
      "error": error
    });
  };

  ProductBOM.save = function() {
    return $.post("/product/product_bom", new ProductBOM(), function(t) {
      if (t) {
        alert("Cadastrado com sucesso!");
        return ProductBOM.getListFromServer();
      } else {
        return alert("Erro ao cadastrar!");
      }
    });
  };

  $(function() {
    ProductBOM.getListFromServer();
    DataManager.getActivities(function(activitys) {
      var obj, ret, _i, _len;
      ret = "<option value='' selected=true>Selecione um Serviço</option>";
      for (_i = 0, _len = activitys.length; _i < _len; _i++) {
        obj = activitys[_i];
        ret += "<option value='" + obj.id + "'>" + obj.name + "</option>";
      }
      $("#product").html(ret);
      return $("#product").change();
    });
    return $("#b_save").click(function() {
      return ProductBOM.save();
    });
  });

}).call(this);
